{% set name = "brotli-asgi" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2d6eca4b97af19716af05bbe0d4d79cffb0b0947100c188da9ed089f5b7bc2f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - brotli-python >=1.0.9
    - pip
    - python {{ python_min }}
    - starlette >=0.25.0
  run:
    - brotli-python >=1.0.9
    - python >={{ python_min }}
    - starlette >=0.25.0

test:
  imports:
    - brotli_asgi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fullonic/brotli-asgi
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A compression AGSI middleware using brotli

extra:
  recipe-maintainers:
    - fullonic
    - dcfidalgo
